export default[
{question: "I. Author of Harry Potter",
options:["A)Conan Doyle", "B)J.K.ROWLING","C)Agastha Christie", "D)Charles Dickens"],
answer: 1,
},
{question: "II. Author of Ponniyin Selvan",
options:["A)Kalki", "B)Sujatha","C)Sandilyan", "D)Indira Parthasarathy"],
answer: 0,
},
{question: "III. What is the name of Harry Potter's Pet",
options:["A)Pygmy Puff", "B)Crookshanks","C)Hedwig", "D)Scabbers"],
answer: 2,
},
{question: "IV. Who built Thanjavur temple",
options:["A)Karikal Cholan", "B)Raja Raja Cholan","C)Rajendra Cholan", "D)Sundara Cholan"],
answer: 1,
},
{question: "V. Which is not a Voldemort name",
options:["A)You Know Who", "B)Tom Riddle", "C)The Dark Lord", "D)Nangini"],
answer: 3,
}
]